name: Organize Imports

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  organize-imports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Run isort
        run: |
          isort .

      - name: Check for changes
        run: |
          if ! git diff --quiet; then
            echo "isort made changes. Please commit them." && exit 1;
          fi
